name: clash-brainfuck
version: 0.1.0
category: hardware

dependencies:
  - base >= 4.7 && < 5
  - clash-prelude
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

  - retroclash-lib
  - retroclash-sim
  - clash-shake

  - mtl
  - array
  - monad-loops
  - barbies ^>= 2.0.1
  - barbies-th
  - lens
  - bytestring
  - temporary

# Anything that Clash uses by default should go here
default-extensions:
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - ExplicitForAll
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MagicHash
  - MonoLocalBinds
  - NoImplicitPrelude
  - NoStarIsType
  - NoStrictData
  - NoStrict
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators

ghc-options:
  -fexpose-all-unfoldings -fno-worker-wrapper
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

source-dirs:
  - src

executables:
  bf-structured:
    main: structured.hs

  bf-bytecode:
    main: bytecode.hs

  bf-external-memory:
    main: external-memory.hs

  bf-sim-cpu:
    main: sim-cpu.hs

  bf-sim-logicboard:
    main: sim-logicboard.hs
