resolver: lts-15.2

extra-deps:
  - barbies-2.0.0.0
  - barbies-th-0.1
  - ghc-typelits-extra-0.4
  - ghc-typelits-natnormalise-0.7.2

  - clash-compiler/clash-prelude

  - concurrent-supply-0.1.8
  - shake-0.18.2

flags:
    clash-prelude:
      multiple-hidden: false



